oauth/src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Uid\Uuid;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @method string getUserIdentifier()
 */
#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[ORM\UniqueConstraint(name: 'U_user_email', columns: ['email'])]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'NONE')]
    #[ORM\Column(type: 'string', columnDefinition: 'CHAR(36) NOT NULL')]
    private string $id;

    #[Assert\NotBlank]
    #[Assert\Length(
        min: 2,
        max: 20
    )]
    #[ORM\Column(type: 'string', length: 50)]
    private ?string $firstName;

    #[Assert\NotBlank]
    #[Assert\Length(
        min: 2,
        max: 20
    )]
    #[ORM\Column(type: 'string', length: 50)]
    private ?string $lastName;

    #[Assert\NotBlank]
    #[Assert\Email]
    #[ORM\Column(type: 'string', length: 100)]
    private string $email;

    #[Assert\NotBlank]
    #[Assert\Length(
        min: 8,
        max: 30,
    )]
    #[ORM\Column(type: 'string', length: 100)]
    private ?string $password;

    public function __construct()
    {
        $this->id = Uuid::v4()->toRfc4122();
    }

    public function getId(): string
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): string
    {
        return $this->email;
    }

    public function setEmail(string $email): void
    {
        $this->email = $email;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(?string $password): void
    {
        $this->password = $password;
    }

    public function getRoles(): array
    {
        return ['ROLE_USER'];
    }

    public function getSalt(): ?string
    {
        return null;
    }

    public function eraseCredentials(): void
    {
    }

    public function getUsername(): string
    {
        return $this->email;
    }

    public function __call(string $name, array $arguments)
    {
        // TODO: Implement @method string getUserIdentifier()
    }
}

oauth/src/Form/UserType.php
<?php

declare(strict_types=1);

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('firstName')
            ->add('lastName')
            ->add('email', EmailType::class)
            ->add('password', RepeatedType::class, [
                'type' => PasswordType::class,
                'invalid_message' => 'The password fields must match.',
                'first_options' => ['label' => 'Password'],
                'second_options' => ['label' => 'Confirm Password'],
            ])
            ->add('save', SubmitType::class);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

oauth/src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/api')]
class ProfileController extends AbstractController
{
    #[Route('/me', name: 'oauth_api_me', methods: ['GET'])]
    public function me(): Response
    {
        /** @var User $user */
        $user = $this->getUser();

        return new JsonResponse([
            'id' => $user->getId(),
            'email' => $user->getEmail(),
        ]);
    }
}

oauth/src/Controller/SecurityController.php
<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\User;
use App\EventListener\SignedAuthorizationRequestSubscriber;
use App\Form\UserType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\UriSigner;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    private UriSigner $uriSigner;
    private string $authorizationRoute;

    public function __construct(UriSigner $uriSigner, string $authorizationRoute = 'oauth2_authorize')
    {
        $this->uriSigner = $uriSigner;
        $this->authorizationRoute = $authorizationRoute;
    }

    #[Route('/register', name: 'oauth_register', methods: ['GET', 'POST'])]
    public function register(Request $request, EntityManagerInterface $entityManager, UserPasswordHasherInterface $hasher): Response
    {
        $user = new User();

        $form = $this->createForm(UserType::class, $user);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user->setPassword($hasher->hashPassword($user, $form->getData()->getPassword()));

            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('oauth_login');
        }

        return $this->renderForm('user/register.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('/login', name: 'oauth_login')]
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        if ($this->getUser()) {
            return $this->redirectToRoute('target_path');
        }

        $error = $authenticationUtils->getLastAuthenticationError();
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('user/login.html.twig', [
            'last_username' => $lastUsername,
            'error' => $error,
        ]);
    }

    /**
     * @Route("/authorize/decide", name="oauth2_decision")
     */
    public function decisionAction(Request $request): Response
    {
        return $this->render('user/decide.html.twig', [
            'allow_uri' => $this->buildDecidedUri($request, true),
            'deny_uri' => $this->buildDecidedUri($request, false),
        ]);
    }

    private function buildDecidedUri(Request $request, bool $allowed): string
    {
        $currentQuery = $request->query->all();
        $decidedQuery = array_merge($currentQuery, [SignedAuthorizationRequestSubscriber::ATTRIBUTE_DECISION => $this->buildDecisionValue($allowed)]);
        $decidedUri = $this->generateUrl($this->authorizationRoute, $decidedQuery);

        return $this->uriSigner->sign($decidedUri);
    }

    private function buildDecisionValue(bool $allowed): string
    {
        return $allowed ? SignedAuthorizationRequestSubscriber::ATTRIBUTE_DECISION_ALLOW : '';
    }
}

oauth/templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Brisbane OAuth!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
    <div class="container">
        {% block body %}{% endblock %}
    </div>
    </body>
</html>

oauth/templates/user/decide.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="row">
    <div>
        <a href="{{ allow_uri }}">Allow</a> | <a href="{{ deny_uri }}">Deny</a>
    </div>
</div>
{% endblock %}

oauth/templates/user/login.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row">
        <div class="col-6 offset-3">
            <h1>Login</h1>
            {% if error %}
                <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
                <div>Remove later: {{ error.message }}</div>
            {% endif %}

            {% if app.user %}
                <div class="mb-3">
                    You are logged in as {{ app.user.username }}, <a href="{{ path('app_logout') }}">Logout</a>
                </div>
            {% endif %}
            <form action="{{ path('oauth_login') }}" method="post">
                <div class="form-group">
                    <label for="username">Email address</label>
                    <input name="_username" type="email" value="{{ last_username }}" class="form-control" id="username"
                           aria-describedby="emailHelp" placeholder="Enter email">
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input name="_password" type="password" class="form-control" id="password" placeholder="Password">
                </div>
                <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}" >
                <button type="submit" class="btn btn-primary mt-3">Submit</button>
            </form>
        </div>
    </div>

{% endblock %}

oauth/templates/user/register.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <section class="vh-100 gradient-custom">
        <div class="container py-5 h-100">
            <div class="row justify-content-center align-items-center h-100">
                <div class="col-12 col-lg-9 col-xl-7">
                    <div class="card shadow-2-strong card-registration bg-light bg-gradient" style="border-radius: 15px;">
                        <div class="card-body p-4 p-md-5">
                            <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">Registration Form</h3>
                            {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}

                            <div class="row">

                                <div class="col-md-6 mb-4">

                                    <div class="form-outline">
                                        {{ form_row(form.firstName, {'attr': {'class': 'form-control form-control-lg'}}) }}
                                    </div>

                                </div>
                                <div class="col-md-6 mb-4">

                                    <div class="form-outline">
                                        {{ form_row(form.lastName, {'attr': {'class': 'form-control form-control-lg'}}) }}
                                    </div>

                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12 mb-4 d-flex align-items-center">

                                    <div class="form-outline datepicker w-100">
                                        {{ form_row(form.email, {'attr': {'class': 'form-control form-control-lg'}}) }}
                                    </div>

                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6 mb-4 pb-2">

                                    <div class="form-outline">
                                        {{ form_row(form.password.first, {'attr': {'class': 'form-control form-control-lg'}}) }}
                                    </div>

                                </div>
                                <div class="col-md-6 mb-4 pb-2">

                                    <div class="form-outline">
                                        {{ form_row(form.password.second, {'attr': {'class': 'form-control form-control-lg'}}) }}
                                    </div>

                                </div>
                            </div>

                            <div class="mt-4 pt-2">
                                {{ form_row(form.save, { 'label': 'Register' }, {'attr': {'class': 'btn btn-primary btn-lg'}}) }}
                            </div>
                            {{ form_rest(form) }}
                            {{ form_end(form) }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}